name: golangci-lint
on: 
  pull_request:

jobs:
  resolve-modules:
    name: Resolve Modules
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - id: set-matrix
        run: ./tools/resolve-modules.sh
  golangci:
    name: Linter
    needs: resolve-modules
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
    steps:
      - uses: actions/setup-go@v4
        with: 
            go-version: 1.20
            cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.52.0
          working-directory: ${{ matrix.workdir }}
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true